#!/usr/bin/env ruby

require_relative "../wikipedia_mapping"
require_relative "../vandal"
require_relative "../poet"

if ARGV.size == 0
  puts "No term"
else
  term = ARGV[0]
  if WikipediaMapping.new("wiki-terms.yml").mapping.keys.include?(term)
    poet = Poet.new


    puts " __________________________________________"
    puts " "
    puts "    Po(e)sible Vandalismo :: #{term.upcase} "
    puts " __________________________________________"
    puts " "


    puts "    #{term.upcase}  "
    puts " "
    puts "    " + poet.poem(term).split("\n") * "\n    "
    puts " "
    puts "                    ***                      "
  else
    puts "#{term} not found in wiki-terms.yml"
  end
end
